// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --local > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          name: string;
          avatar_url: string | null;
          email: string;
          created_at: string;
        };
        Insert: {
          id: string;
          name: string;
          avatar_url?: string | null;
          email: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          avatar_url?: string | null;
          email?: string;
          created_at?: string;
        };
      };
      groups: {
        Row: {
          id: string;
          name: string;
          cover_image: string | null;
          created_by: string;
          baton_deadline_days: number;
          current_baton_holder_id: string | null;
          baton_passed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          cover_image?: string | null;
          created_by: string;
          baton_deadline_days?: number;
          current_baton_holder_id?: string | null;
          baton_passed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          cover_image?: string | null;
          created_by?: string;
          baton_deadline_days?: number;
          current_baton_holder_id?: string | null;
          baton_passed_at?: string | null;
          created_at?: string;
        };
      };
      group_members: {
        Row: {
          group_id: string;
          user_id: string;
          role: "owner" | "member";
          joined_at: string;
        };
        Insert: {
          group_id: string;
          user_id: string;
          role?: "owner" | "member";
          joined_at?: string;
        };
        Update: {
          group_id?: string;
          user_id?: string;
          role?: "owner" | "member";
          joined_at?: string;
        };
      };
      group_invitations: {
        Row: {
          id: string;
          group_id: string;
          token: string;
          created_by: string;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          token: string;
          created_by: string;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          token?: string;
          created_by?: string;
          expires_at?: string | null;
          created_at?: string;
        };
      };
      entries: {
        Row: {
          id: string;
          group_id: string;
          author_id: string;
          body: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          author_id: string;
          body?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          author_id?: string;
          body?: string | null;
          created_at?: string;
        };
      };
      entry_media: {
        Row: {
          id: string;
          entry_id: string;
          type: "image" | "video" | "animation";
          url: string;
          order: number;
          width: number | null;
          height: number | null;
        };
        Insert: {
          id?: string;
          entry_id: string;
          type: "image" | "video" | "animation";
          url: string;
          order: number;
          width?: number | null;
          height?: number | null;
        };
        Update: {
          id?: string;
          entry_id?: string;
          type?: "image" | "video" | "animation";
          url?: string;
          order?: number;
          width?: number | null;
          height?: number | null;
        };
      };
      stamps: {
        Row: {
          id: string;
          name: string;
          type: "lottie" | "apng" | "webp";
          url: string;
          thumbnail_url: string | null;
          scope: "builtin" | "group";
          group_id: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: "lottie" | "apng" | "webp";
          url: string;
          thumbnail_url?: string | null;
          scope?: "builtin" | "group";
          group_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: "lottie" | "apng" | "webp";
          url?: string;
          thumbnail_url?: string | null;
          scope?: "builtin" | "group";
          group_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
      };
      entry_stamps: {
        Row: {
          id: string;
          entry_id: string;
          stamp_id: string;
          x: number;
          y: number;
          scale: number;
          rotation: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          entry_id: string;
          stamp_id: string;
          x: number;
          y: number;
          scale?: number;
          rotation?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          entry_id?: string;
          stamp_id?: string;
          x?: number;
          y?: number;
          scale?: number;
          rotation?: number;
          created_at?: string;
        };
      };
      reactions: {
        Row: {
          entry_id: string;
          user_id: string;
          stamp_id: string;
          created_at: string;
        };
        Insert: {
          entry_id: string;
          user_id: string;
          stamp_id: string;
          created_at?: string;
        };
        Update: {
          entry_id?: string;
          user_id?: string;
          stamp_id?: string;
          created_at?: string;
        };
      };
      flipbooks: {
        Row: {
          id: string;
          entry_id: string;
          fps: number;
          loop: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          entry_id: string;
          fps?: number;
          loop?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          entry_id?: string;
          fps?: number;
          loop?: boolean;
          created_at?: string;
        };
      };
      flipbook_frames: {
        Row: {
          id: string;
          flipbook_id: string;
          order: number;
          canvas_json: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          flipbook_id: string;
          order: number;
          canvas_json: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          flipbook_id?: string;
          order?: number;
          canvas_json?: string;
          created_at?: string;
        };
      };
      notification_preferences: {
        Row: {
          user_id: string;
          email_enabled: boolean;
          push_enabled: boolean;
          push_subscription: Json | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          email_enabled?: boolean;
          push_enabled?: boolean;
          push_subscription?: Json | null;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          email_enabled?: boolean;
          push_enabled?: boolean;
          push_subscription?: Json | null;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
